let full_order = [
    { 
      "symbol": "SAND-USDT", 
      "orderId": 1846216338172170200, 
      "side": "BUY", 
      "positionSide": "BOTH", 
      "type": "STOP_MARKET", 
      "origQty": "13", 
      "price": "0", 
      "executedQty": "0", 
      "avgPrice": "0.2645", 
      "cumQuote": "0", 
      "stopPrice": "0.2802", 
      "profit": "0.0", 
      "commission": "0.0", 
      "status": "NEW", 
      "time": 1729007251000, 
      "updateTime": 1729007251000, 
      "clientOrderId": "", 
      "leverage": "8X", 
      "takeProfit": { 
        "type": "", 
        "quantity": 0, 
        "stopPrice": 0, 
        "price": 0, 
        "workingType": "", 
        "stopGuaranteed": "" 
      }, 
      "stopLoss": { 
        "type": "", 
        "quantity": 0, 
        "stopPrice": 0, 
        "price": 0, 
        "workingType": "", 
        "stopGuaranteed": "" 
      }, 
      "advanceAttr": 0, 
      "positionID": 0, 
      "takeProfitEntrustPrice": 0, 
      "stopLossEntrustPrice": 0, 
      "orderType": "", 
      "workingType": "CONTRACT_PRICE", 
      "onlyOnePosition": true, 
      "reduceOnly": true, 
      "postOnly": false, 
      "stopGuaranteed": "false", 
      "triggerOrderId": 0, 
      "trailingStopRate": 0, 
      "trailingStopDistance": 0 
    }, 
    { 
      "symbol": "SAND-USDT", 
      "orderId": 1846216329007616000, 
      "side": "BUY", 
      "positionSide": "BOTH", 
      "type": "TAKE_PROFIT_MARKET", 
      "origQty": "13", 
      "price": "0", 
      "executedQty": "0", 
      "avgPrice": "0.0", 
      "cumQuote": "0", 
      "stopPrice": "0.2506", 
      "profit": "0.0", 
      "commission": "0.0", 
      "status": "NEW", 
      "time": 1729007249000, 
      "updateTime": 1729007249000, 
      "clientOrderId": "", 
      "leverage": "8X", 
      "takeProfit": { 
        "type": "", 
        "quantity": 0, 
        "stopPrice": 0, 
        "price": 0, 
        "workingType": "", 
        "stopGuaranteed": "" 
      }, 
      "stopLoss": { 
        "type": "", 
        "quantity": 0, 
        "stopPrice": 0, 
        "price": 0, 
        "workingType": "", 
        "stopGuaranteed": "" 
      }, 
      "advanceAttr": 0, 
      "positionID": 0, 
      "takeProfitEntrustPrice": 0, 
      "stopLossEntrustPrice": 0, 
      "orderType": "", 
      "workingType": "CONTRACT_PRICE", 
      "onlyOnePosition": true, 
      "reduceOnly": true, 
      "postOnly": false, 
      "stopGuaranteed": "false", 
      "triggerOrderId": 0, 
      "trailingStopRate": 0, 
      "trailingStopDistance": 0 
    }, 
    { 
      "positionId": "1846204222094184448", 
      "symbol": "SAND-USDT", 
      "currency": "USDT", 
      "positionAmt": "13", 
      "availableAmt": "13", 
      "positionSide": "SHORT", 
      "isolated": true, 
      "avgPrice": "0.2645", 
      "initialMargin": "0.4298", 
      "margin": "0.4181", 
      "leverage": 8, 
      "unrealizedProfit": "-0.0118", 
      "realisedProfit": "-0.0017", 
      "liquidationPrice": 0.2946, 
      "pnlRatio": "-0.0273", 
      "maxMarginReduction": "0.0000", 
      "riskRate": "0.0825", 
      "markPrice": "0.2654", 
      "positionValue": "3.4503", 
      "onlyOnePosition": true, 
      "updateTime": 1729004362024 
    }
  ];
  
  // Extract positionId using forEach
  full_order.forEach(order => {
    if (order.positionId) {
      console.log("Position ID:", order.positionId);
    }
  });
  